<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-22T09:24:54 WEST" name="Suite" finished-at="2024-07-22T09:25:49 WEST" duration-ms="55757">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.addProductErrorValidation()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" name="addProductErrorValidation" class="WebAutomation.Tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" name="submitOrder" class="WebAutomation.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-07-22T09:24:54 WEST" name="Error Validation Test" finished-at="2024-07-22T09:25:46 WEST" duration-ms="52475">
      <class name="WebAutomation.Tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:24:54 WEST" name="launchApplication" finished-at="2024-07-22T09:25:00 WEST" duration-ms="6270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="addProductErrorValidation()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:00 WEST" name="addProductErrorValidation" finished-at="2024-07-22T09:25:13 WEST" duration-ms="13041" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:13 WEST" name="tearDown" finished-at="2024-07-22T09:25:21 WEST" duration-ms="8025" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:21 WEST" name="launchApplication" finished-at="2024-07-22T09:25:27 WEST" duration-ms="5635" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:27 WEST" name="loginErrorValidation" finished-at="2024-07-22T09:25:31 WEST" duration-ms="4037" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.XX] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.XX] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at WebAutomation.Tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:31 WEST" name="tearDown" finished-at="2024-07-22T09:25:32 WEST" duration-ms="1388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:32 WEST" name="launchApplication" finished-at="2024-07-22T09:25:37 WEST" duration-ms="4274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:37 WEST" name="loginErrorValidation" finished-at="2024-07-22T09:25:44 WEST" duration-ms="7313" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.XX] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.XX] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at WebAutomation.Tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:WebAutomation.Tests.ErrorValidationTest@13d73f29]" started-at="2024-07-22T09:25:45 WEST" name="tearDown" finished-at="2024-07-22T09:25:46 WEST" duration-ms="1285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- WebAutomation.Tests.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2024-07-22T09:24:54 WEST" name="Submit Order Test" finished-at="2024-07-22T09:25:49 WEST" duration-ms="55757">
      <class name="WebAutomation.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:24:54 WEST" name="launchApplication" finished-at="2024-07-22T09:25:03 WEST" duration-ms="8487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:03 WEST" name="submitOrder" data-provider="getData" finished-at="2024-07-22T09:25:15 WEST" duration-ms="12730" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Abc123456789, product=ADIDAS ORIGINAL, email=Test2024@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:15 WEST" name="tearDown" finished-at="2024-07-22T09:25:21 WEST" duration-ms="5310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:21 WEST" name="launchApplication" finished-at="2024-07-22T09:25:29 WEST" duration-ms="8546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:29 WEST" name="submitOrder" data-provider="getData" finished-at="2024-07-22T09:25:37 WEST" duration-ms="8055" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Abc1234567890, product=ZARA COAT 3, email=Test2030@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:37 WEST" name="tearDown" finished-at="2024-07-22T09:25:38 WEST" duration-ms="1113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:38 WEST" name="launchApplication" finished-at="2024-07-22T09:25:45 WEST" duration-ms="6360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest()[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:45 WEST" name="orderHistoryTest" finished-at="2024-07-22T09:25:49 WEST" depends-on-methods="WebAutomation.Tests.SubmitOrderTest.submitOrder" duration-ms="4377" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:WebAutomation.Tests.SubmitOrderTest@239a307b]" started-at="2024-07-22T09:25:49 WEST" name="tearDown" finished-at="2024-07-22T09:25:49 WEST" duration-ms="407" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- WebAutomation.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
